// Auto-generated from datasets/country-codes (ISO 3166 + ITU E.164)

export const PHONE_COUNTRIES_DATA = [
  { iso: 'MA', dial: '+212', name: { fr: "Maroc", en: "Morocco" } },
  { iso: 'AF', dial: '+93', name: { fr: "Afghanistan", en: "Afghanistan" } },
  { iso: 'ZA', dial: '+27', name: { fr: "Afrique du Sud", en: "South Africa" } },
  { iso: 'AL', dial: '+355', name: { fr: "Albanie", en: "Albania" } },
  { iso: 'DZ', dial: '+213', name: { fr: "Algérie", en: "Algeria" } },
  { iso: 'DE', dial: '+49', name: { fr: "Allemagne", en: "Germany" } },
  { iso: 'AD', dial: '+376', name: { fr: "Andorre", en: "Andorra" } },
  { iso: 'AO', dial: '+244', name: { fr: "Angola", en: "Angola" } },
  { iso: 'AQ', dial: '+672', name: { fr: "Antarctique", en: "Antarctica" } },
  { iso: 'SA', dial: '+966', name: { fr: "Arabie saoudite", en: "Saudi Arabia" } },
  { iso: 'AR', dial: '+54', name: { fr: "Argentine", en: "Argentina" } },
  { iso: 'AM', dial: '+374', name: { fr: "Arménie", en: "Armenia" } },
  { iso: 'AW', dial: '+297', name: { fr: "Aruba", en: "Aruba" } },
  { iso: 'AU', dial: '+61', name: { fr: "Australie", en: "Australia" } },
  { iso: 'AT', dial: '+43', name: { fr: "Autriche", en: "Austria" } },
  { iso: 'AZ', dial: '+994', name: { fr: "Azerbaïdjan", en: "Azerbaijan" } },
  { iso: 'BH', dial: '+973', name: { fr: "Bahreïn", en: "Bahrain" } },
  { iso: 'BD', dial: '+880', name: { fr: "Bangladesh", en: "Bangladesh" } },
  { iso: 'BY', dial: '+375', name: { fr: "Bélarus", en: "Belarus" } },
  { iso: 'BE', dial: '+32', name: { fr: "Belgique", en: "Belgium" } },
  { iso: 'BZ', dial: '+501', name: { fr: "Belize", en: "Belize" } },
  { iso: 'BJ', dial: '+229', name: { fr: "Bénin", en: "Benin" } },
  { iso: 'BT', dial: '+975', name: { fr: "Bhoutan", en: "Bhutan" } },
  { iso: 'BO', dial: '+591', name: { fr: "Bolivie", en: "Bolivia" } },
  { iso: 'BQ', dial: '+599', name: { fr: "Bonaire, Saint-Eustache et Saba", en: "Bonaire, Sint Eustatius and Saba" } },
  { iso: 'BA', dial: '+387', name: { fr: "Bosnie-Herzégovine", en: "Bosnia and Herzegovina" } },
  { iso: 'BW', dial: '+267', name: { fr: "Botswana", en: "Botswana" } },
  { iso: 'BR', dial: '+55', name: { fr: "Brésil", en: "Brazil" } },
  { iso: 'BN', dial: '+673', name: { fr: "Brunéi Darussalam", en: "Brunei Darussalam" } },
  { iso: 'BG', dial: '+359', name: { fr: "Bulgarie", en: "Bulgaria" } },
  { iso: 'BF', dial: '+226', name: { fr: "Burkina Faso", en: "Burkina Faso" } },
  { iso: 'BI', dial: '+257', name: { fr: "Burundi", en: "Burundi" } },
  { iso: 'CV', dial: '+238', name: { fr: "Cabo Verde", en: "Cabo Verde" } },
  { iso: 'KH', dial: '+855', name: { fr: "Cambodge", en: "Cambodia" } },
  { iso: 'CM', dial: '+237', name: { fr: "Cameroun", en: "Cameroon" } },
  { iso: 'CA', dial: '+1', name: { fr: "Canada", en: "Canada" } },
  { iso: 'CL', dial: '+56', name: { fr: "Chili", en: "Chile" } },
  { iso: 'CN', dial: '+86', name: { fr: "Chine", en: "China" } },
  { iso: 'HK', dial: '+852', name: { fr: "Chine, région administrative spéciale de Hong Kong", en: "China, Hong Kong Special Administrative Region" } },
  { iso: 'MO', dial: '+853', name: { fr: "Chine, région administrative spéciale de Macao", en: "China, Macao Special Administrative Region" } },
  { iso: 'CY', dial: '+357', name: { fr: "Chypre", en: "Cyprus" } },
  { iso: 'CO', dial: '+57', name: { fr: "Colombie", en: "Colombia" } },
  { iso: 'KM', dial: '+269', name: { fr: "Comores", en: "Comoros" } },
  { iso: 'CG', dial: '+242', name: { fr: "Congo", en: "Congo" } },
  { iso: 'CR', dial: '+506', name: { fr: "Costa Rica", en: "Costa Rica" } },
  { iso: 'CI', dial: '+225', name: { fr: "Côte d’Ivoire", en: "Ivory Coast" } },
  { iso: 'HR', dial: '+385', name: { fr: "Croatie", en: "Croatia" } },
  { iso: 'CU', dial: '+53', name: { fr: "Cuba", en: "Cuba" } },
  { iso: 'CW', dial: '+599', name: { fr: "Curaçao", en: "Curaçao" } },
  { iso: 'DK', dial: '+45', name: { fr: "Danemark", en: "Denmark" } },
  { iso: 'DJ', dial: '+253', name: { fr: "Djibouti", en: "Djibouti" } },
  { iso: 'EG', dial: '+20', name: { fr: "Égypte", en: "Egypt" } },
  { iso: 'SV', dial: '+503', name: { fr: "El Salvador", en: "El Salvador" } },
  { iso: 'AE', dial: '+971', name: { fr: "Émirats arabes unis", en: "United Arab Emirates" } },
  { iso: 'EC', dial: '+593', name: { fr: "Équateur", en: "Ecuador" } },
  { iso: 'ER', dial: '+291', name: { fr: "Érythrée", en: "Eritrea" } },
  { iso: 'ES', dial: '+34', name: { fr: "Espagne", en: "Spain" } },
  { iso: 'EE', dial: '+372', name: { fr: "Estonie", en: "Estonia" } },
  { iso: 'SZ', dial: '+268', name: { fr: "Eswatini", en: "Eswatini" } },
  { iso: 'PS', dial: '+970', name: { fr: "État de Palestine", en: "State of Palestine" } },
  { iso: 'US', dial: '+1', name: { fr: "États-Unis d’Amérique", en: "United States of America" } },
  { iso: 'ET', dial: '+251', name: { fr: "Éthiopie", en: "Ethiopia" } },
  { iso: 'RU', dial: '+7', name: { fr: "Fédération de Russie", en: "Russian Federation" } },
  { iso: 'FJ', dial: '+679', name: { fr: "Fidji", en: "Fiji" } },
  { iso: 'FI', dial: '+358', name: { fr: "Finlande", en: "Finland" } },
  { iso: 'FR', dial: '+33', name: { fr: "France", en: "France" } },
  { iso: 'GA', dial: '+241', name: { fr: "Gabon", en: "Gabon" } },
  { iso: 'GM', dial: '+220', name: { fr: "Gambie", en: "Gambia" } },
  { iso: 'GE', dial: '+995', name: { fr: "Géorgie", en: "Georgia" } },
  { iso: 'GS', dial: '+500', name: { fr: "Géorgie du Sud-et-les Îles Sandwich du Sud", en: "South Georgia and the South Sandwich Islands" } },
  { iso: 'GH', dial: '+233', name: { fr: "Ghana", en: "Ghana" } },
  { iso: 'GI', dial: '+350', name: { fr: "Gibraltar", en: "Gibraltar" } },
  { iso: 'GR', dial: '+30', name: { fr: "Grèce", en: "Greece" } },
  { iso: 'GL', dial: '+299', name: { fr: "Groenland", en: "Greenland" } },
  { iso: 'GP', dial: '+590', name: { fr: "Guadeloupe", en: "Guadeloupe" } },
  { iso: 'GT', dial: '+502', name: { fr: "Guatemala", en: "Guatemala" } },
  { iso: 'GG', dial: '+44', name: { fr: "Guernesey", en: "Guernsey" } },
  { iso: 'GN', dial: '+224', name: { fr: "Guinée", en: "Guinea" } },
  { iso: 'GQ', dial: '+240', name: { fr: "Guinée équatoriale", en: "Equatorial Guinea" } },
  { iso: 'GW', dial: '+245', name: { fr: "Guinée-Bissau", en: "Guinea-Bissau" } },
  { iso: 'GY', dial: '+592', name: { fr: "Guyana", en: "Guyana" } },
  { iso: 'GF', dial: '+594', name: { fr: "Guyane française", en: "French Guiana" } },
  { iso: 'HT', dial: '+509', name: { fr: "Haïti", en: "Haiti" } },
  { iso: 'HN', dial: '+504', name: { fr: "Honduras", en: "Honduras" } },
  { iso: 'HU', dial: '+36', name: { fr: "Hongrie", en: "Hungary" } },
  { iso: 'BV', dial: '+47', name: { fr: "Île Bouvet", en: "Bouvet Island" } },
  { iso: 'CX', dial: '+61', name: { fr: "Île Christmas", en: "Christmas Island" } },
  { iso: 'IM', dial: '+44', name: { fr: "Île de Man", en: "Isle of Man" } },
  { iso: 'HM', dial: '+672', name: { fr: "Île Heard-et-Îles MacDonald", en: "Heard Island and McDonald Islands" } },
  { iso: 'NF', dial: '+672', name: { fr: "Île Norfolk", en: "Norfolk Island" } },
  { iso: 'CK', dial: '+682', name: { fr: "Îles Cook", en: "Cook Islands" } },
  { iso: 'AX', dial: '+358', name: { fr: "Îles d’Åland", en: "Åland Islands" } },
  { iso: 'CC', dial: '+61', name: { fr: "Îles des Cocos", en: "Cocos (Keeling) Islands" } },
  { iso: 'FK', dial: '+500', name: { fr: "Îles Falkland", en: "Falkland Islands" } },
  { iso: 'FO', dial: '+298', name: { fr: "Îles Féroé", en: "Faroe Islands" } },
  { iso: 'MH', dial: '+692', name: { fr: "Îles Marshall", en: "Marshall Islands" } },
  { iso: 'SB', dial: '+677', name: { fr: "Îles Salomon", en: "Solomon Islands" } },
  { iso: 'SJ', dial: '+47', name: { fr: "Îles Svalbard-et-Jan Mayen", en: "Svalbard and Jan Mayen Islands" } },
  { iso: 'WF', dial: '+681', name: { fr: "Îles Wallis-et-Futuna", en: "Wallis and Futuna Islands" } },
  { iso: 'IN', dial: '+91', name: { fr: "Inde", en: "India" } },
  { iso: 'ID', dial: '+62', name: { fr: "Indonésie", en: "Indonesia" } },
  { iso: 'IR', dial: '+98', name: { fr: "Iran", en: "Iran" } },
  { iso: 'IQ', dial: '+964', name: { fr: "Iraq", en: "Iraq" } },
  { iso: 'IE', dial: '+353', name: { fr: "Irlande", en: "Ireland" } },
  { iso: 'IS', dial: '+354', name: { fr: "Islande", en: "Iceland" } },
  { iso: 'IL', dial: '+972', name: { fr: "Israël", en: "Israel" } },
  { iso: 'IT', dial: '+39', name: { fr: "Italie", en: "Italy" } },
  { iso: 'JP', dial: '+81', name: { fr: "Japon", en: "Japan" } },
  { iso: 'JE', dial: '+44', name: { fr: "Jersey", en: "Jersey" } },
  { iso: 'JO', dial: '+962', name: { fr: "Jordanie", en: "Jordan" } },
  { iso: 'KZ', dial: '+7', name: { fr: "Kazakhstan", en: "Kazakhstan" } },
  { iso: 'KE', dial: '+254', name: { fr: "Kenya", en: "Kenya" } },
  { iso: 'KG', dial: '+996', name: { fr: "Kirghizistan", en: "Kyrgyzstan" } },
  { iso: 'KI', dial: '+686', name: { fr: "Kiribati", en: "Kiribati" } },
  { iso: 'KW', dial: '+965', name: { fr: "Koweït", en: "Kuwait" } },
  { iso: 'LS', dial: '+266', name: { fr: "Lesotho", en: "Lesotho" } },
  { iso: 'LV', dial: '+371', name: { fr: "Lettonie", en: "Latvia" } },
  { iso: 'LB', dial: '+961', name: { fr: "Liban", en: "Lebanon" } },
  { iso: 'LR', dial: '+231', name: { fr: "Libéria", en: "Liberia" } },
  { iso: 'LY', dial: '+218', name: { fr: "Libye", en: "Libya" } },
  { iso: 'LI', dial: '+423', name: { fr: "Liechtenstein", en: "Liechtenstein" } },
  { iso: 'LT', dial: '+370', name: { fr: "Lituanie", en: "Lithuania" } },
  { iso: 'LU', dial: '+352', name: { fr: "Luxembourg", en: "Luxembourg" } },
  { iso: 'MK', dial: '+389', name: { fr: "Macédoine du Nord", en: "North Macedonia" } },
  { iso: 'MG', dial: '+261', name: { fr: "Madagascar", en: "Madagascar" } },
  { iso: 'MY', dial: '+60', name: { fr: "Malaisie", en: "Malaysia" } },
  { iso: 'MW', dial: '+265', name: { fr: "Malawi", en: "Malawi" } },
  { iso: 'MV', dial: '+960', name: { fr: "Maldives", en: "Maldives" } },
  { iso: 'ML', dial: '+223', name: { fr: "Mali", en: "Mali" } },
  { iso: 'MT', dial: '+356', name: { fr: "Malte", en: "Malta" } },
  { iso: 'MQ', dial: '+596', name: { fr: "Martinique", en: "Martinique" } },
  { iso: 'MU', dial: '+230', name: { fr: "Maurice", en: "Mauritius" } },
  { iso: 'MR', dial: '+222', name: { fr: "Mauritanie", en: "Mauritania" } },
  { iso: 'YT', dial: '+262', name: { fr: "Mayotte", en: "Mayotte" } },
  { iso: 'MX', dial: '+52', name: { fr: "Mexique", en: "Mexico" } },
  { iso: 'FM', dial: '+691', name: { fr: "Micronésie", en: "Micronesia" } },
  { iso: 'MC', dial: '+377', name: { fr: "Monaco", en: "Monaco" } },
  { iso: 'MN', dial: '+976', name: { fr: "Mongolie", en: "Mongolia" } },
  { iso: 'ME', dial: '+382', name: { fr: "Monténégro", en: "Montenegro" } },
  { iso: 'MZ', dial: '+258', name: { fr: "Mozambique", en: "Mozambique" } },
  { iso: 'MM', dial: '+95', name: { fr: "Myanmar", en: "Myanmar" } },
  { iso: 'NA', dial: '+264', name: { fr: "Namibie", en: "Namibia" } },
  { iso: 'NR', dial: '+674', name: { fr: "Nauru", en: "Nauru" } },
  { iso: 'NP', dial: '+977', name: { fr: "Népal", en: "Nepal" } },
  { iso: 'NI', dial: '+505', name: { fr: "Nicaragua", en: "Nicaragua" } },
  { iso: 'NE', dial: '+227', name: { fr: "Niger", en: "Niger" } },
  { iso: 'NG', dial: '+234', name: { fr: "Nigéria", en: "Nigeria" } },
  { iso: 'NU', dial: '+683', name: { fr: "Nioué", en: "Niue" } },
  { iso: 'NO', dial: '+47', name: { fr: "Norvège", en: "Norway" } },
  { iso: 'NC', dial: '+687', name: { fr: "Nouvelle-Calédonie", en: "New Caledonia" } },
  { iso: 'NZ', dial: '+64', name: { fr: "Nouvelle-Zélande", en: "New Zealand" } },
  { iso: 'OM', dial: '+968', name: { fr: "Oman", en: "Oman" } },
  { iso: 'UG', dial: '+256', name: { fr: "Ouganda", en: "Uganda" } },
  { iso: 'UZ', dial: '+998', name: { fr: "Ouzbékistan", en: "Uzbekistan" } },
  { iso: 'PK', dial: '+92', name: { fr: "Pakistan", en: "Pakistan" } },
  { iso: 'PW', dial: '+680', name: { fr: "Palaos", en: "Palau" } },
  { iso: 'PA', dial: '+507', name: { fr: "Panama", en: "Panama" } },
  { iso: 'PG', dial: '+675', name: { fr: "Papouasie-Nouvelle-Guinée", en: "Papua New Guinea" } },
  { iso: 'PY', dial: '+595', name: { fr: "Paraguay", en: "Paraguay" } },
  { iso: 'NL', dial: '+31', name: { fr: "Pays-Bas", en: "Netherlands" } },
  { iso: 'PE', dial: '+51', name: { fr: "Pérou", en: "Peru" } },
  { iso: 'PH', dial: '+63', name: { fr: "Philippines", en: "Philippines" } },
  { iso: 'PN', dial: '+870', name: { fr: "Pitcairn", en: "Pitcairn" } },
  { iso: 'PL', dial: '+48', name: { fr: "Pologne", en: "Poland" } },
  { iso: 'PF', dial: '+689', name: { fr: "Polynésie française", en: "French Polynesia" } },
  { iso: 'PR', dial: '+1', name: { fr: "Porto Rico", en: "Puerto Rico" } },
  { iso: 'PT', dial: '+351', name: { fr: "Portugal", en: "Portugal" } },
  { iso: 'QA', dial: '+974', name: { fr: "Qatar", en: "Qatar" } },
  { iso: 'SY', dial: '+963', name: { fr: "République arabe syrienne", en: "Syrian Arab Republic" } },
  { iso: 'CF', dial: '+236', name: { fr: "République centrafricaine", en: "Central African Republic" } },
  { iso: 'KR', dial: '+82', name: { fr: "République de Corée", en: "Republic of Korea" } },
  { iso: 'MD', dial: '+373', name: { fr: "République de Moldova", en: "Republic of Moldova" } },
  { iso: 'CD', dial: '+243', name: { fr: "République démocratique du Congo", en: "Democratic Republic of the Congo" } },
  { iso: 'LA', dial: '+856', name: { fr: "République démocratique populaire lao", en: "Lao People's Democratic Republic" } },
  { iso: 'KP', dial: '+850', name: { fr: "République populaire démocratique de Corée", en: "Democratic People's Republic of Korea" } },
  { iso: 'TZ', dial: '+255', name: { fr: "République-Unie de Tanzanie", en: "United Republic of Tanzania" } },
  { iso: 'RE', dial: '+262', name: { fr: "Réunion", en: "Réunion" } },
  { iso: 'RO', dial: '+40', name: { fr: "Roumanie", en: "Romania" } },
  { iso: 'GB', dial: '+44', name: { fr: "Royaume-Uni de Grande-Bretagne et d’Irlande du Nord", en: "United Kingdom of Great Britain and Northern Ireland" } },
  { iso: 'RW', dial: '+250', name: { fr: "Rwanda", en: "Rwanda" } },
  { iso: 'EH', dial: '+212', name: { fr: "Sahara occidental", en: "Western Sahara" } },
  { iso: 'BL', dial: '+590', name: { fr: "Saint-Barthélemy", en: "Saint Barthélemy" } },
  { iso: 'SM', dial: '+378', name: { fr: "Saint-Marin", en: "San Marino" } },
  { iso: 'MF', dial: '+590', name: { fr: "Saint-Martin", en: "Saint Martin" } },
  { iso: 'PM', dial: '+508', name: { fr: "Saint-Pierre-et-Miquelon", en: "Saint Pierre and Miquelon" } },
  { iso: 'WS', dial: '+685', name: { fr: "Samoa", en: "Samoa" } },
  { iso: 'ST', dial: '+239', name: { fr: "Sao Tomé-et-Principe", en: "Sao Tome and Principe" } },
  { iso: 'SN', dial: '+221', name: { fr: "Sénégal", en: "Senegal" } },
  { iso: 'SC', dial: '+248', name: { fr: "Seychelles", en: "Seychelles" } },
  { iso: 'SL', dial: '+232', name: { fr: "Sierra Leone", en: "Sierra Leone" } },
  { iso: 'SG', dial: '+65', name: { fr: "Singapour", en: "Singapore" } },
  { iso: 'SK', dial: '+421', name: { fr: "Slovaquie", en: "Slovakia" } },
  { iso: 'SI', dial: '+386', name: { fr: "Slovénie", en: "Slovenia" } },
  { iso: 'SO', dial: '+252', name: { fr: "Somalie", en: "Somalia" } },
  { iso: 'SD', dial: '+249', name: { fr: "Soudan", en: "Sudan" } },
  { iso: 'SS', dial: '+211', name: { fr: "Soudan du Sud", en: "South Sudan" } },
  { iso: 'LK', dial: '+94', name: { fr: "Sri Lanka", en: "Sri Lanka" } },
  { iso: 'SE', dial: '+46', name: { fr: "Suède", en: "Sweden" } },
  { iso: 'CH', dial: '+41', name: { fr: "Suisse", en: "Switzerland" } },
  { iso: 'SR', dial: '+597', name: { fr: "Suriname", en: "Suriname" } },
  { iso: 'TJ', dial: '+992', name: { fr: "Tadjikistan", en: "Tajikistan" } },
  { iso: 'TW', dial: '+886', name: { fr: "Taïwan", en: "Taiwan" } },
  { iso: 'TD', dial: '+235', name: { fr: "Tchad", en: "Chad" } },
  { iso: 'CZ', dial: '+420', name: { fr: "Tchéquie", en: "Czechia" } },
  { iso: 'TF', dial: '+262', name: { fr: "Terres australes françaises", en: "French Southern Territories" } },
  { iso: 'IO', dial: '+246', name: { fr: "Territoire britannique de l'océan Indien", en: "British Indian Ocean Territory" } },
  { iso: 'TH', dial: '+66', name: { fr: "Thaïlande", en: "Thailand" } },
  { iso: 'TL', dial: '+670', name: { fr: "Timor-Leste", en: "Timor-Leste" } },
  { iso: 'TG', dial: '+228', name: { fr: "Togo", en: "Togo" } },
  { iso: 'TK', dial: '+690', name: { fr: "Tokélaou", en: "Tokelau" } },
  { iso: 'TO', dial: '+676', name: { fr: "Tonga", en: "Tonga" } },
  { iso: 'TN', dial: '+216', name: { fr: "Tunisie", en: "Tunisia" } },
  { iso: 'TR', dial: '+90', name: { fr: "Türkiye", en: "Türkiye" } },
  { iso: 'TM', dial: '+993', name: { fr: "Turkménistan", en: "Turkmenistan" } },
  { iso: 'TV', dial: '+688', name: { fr: "Tuvalu", en: "Tuvalu" } },
  { iso: 'UA', dial: '+380', name: { fr: "Ukraine", en: "Ukraine" } },
  { iso: 'UY', dial: '+598', name: { fr: "Uruguay", en: "Uruguay" } },
  { iso: 'VU', dial: '+678', name: { fr: "Vanuatu", en: "Vanuatu" } },
  { iso: 'VE', dial: '+58', name: { fr: "Venezuela", en: "Venezuela" } },
  { iso: 'VN', dial: '+84', name: { fr: "Viet Nam", en: "Viet Nam" } },
  { iso: 'YE', dial: '+967', name: { fr: "Yémen", en: "Yemen" } },
  { iso: 'ZM', dial: '+260', name: { fr: "Zambie", en: "Zambia" } },
  { iso: 'ZW', dial: '+263', name: { fr: "Zimbabwe", en: "Zimbabwe" } },
];
