name: Lighthouse CI

on:
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Wait for Vercel preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: preview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ steps.preview.outputs.url }}/
            ${{ steps.preview.outputs.url }}/facultes/management
            ${{ steps.preview.outputs.url }}/programmes/dba-management
          configPath: ./lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
